apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-ms
  template:
    metadata:
      labels:
        app: booking-ms
    spec:
      containers:
      - name: booking-ms
        image: chandan669/booking-ms:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: booking-ms-service
spec:
  selector:
    app: booking-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
