apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-ms
  template:
    metadata:
      labels:
        app: booking-ms
    spec:
      containers:
        - name: booking-ms
          image: chandan669/booking-ms:latest
          ports:
            - containerPort: 8080
